#!/usr/bin/env bash
# =============================================================================
# generate-inventory.sh — the directory is the source of truth for what ships
#
# Counts of agents, skills, and rules were hand-maintained in four places and
# disagreed with each other and with the repo. This regenerates them from disk
# into the marked block in README.md.
#
# Usage:
#   generate-inventory.sh          # rewrite the block
#   generate-inventory.sh --check  # exit 1 if the block is stale (CI)
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m'

cd "$(dirname "$0")/.."

BEGIN='<!-- BEGIN:inventory (generated by scripts/generate-inventory.sh — do not edit) -->'
END='<!-- END:inventory -->'

AGENTS=$(find .claude/agents -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
RULES=$(find .claude/rules -name '*.md' | wc -l | tr -d ' ')

# Vendored skills carry their upstream prefix; everything else is first-party.
OWN=0; VENDORED=0
for d in .claude/skills/*/; do
  [ -f "$d/SKILL.md" ] || continue
  case "$(basename "$d")" in
    android-*|kotlin-*) VENDORED=$((VENDORED + 1)) ;;
    *)                  OWN=$((OWN + 1)) ;;
  esac
done

# Rule count by domain, for the table.
domains=""
for dir in .claude/rules/*/; do
  d=$(basename "$dir")
  n=$(find "$dir" -name '*.md' | wc -l | tr -d ' ')
  domains="${domains}| \`${d}/\` | ${n} |"$'\n'
done

block=$(mktemp)
{
  echo "$BEGIN"
  echo
  echo "| What | Count |"
  echo "|---|---|"
  echo "| Agents | $AGENTS |"
  echo "| Skills (first-party) | $OWN |"
  echo "| Skills (vendored — \`android-*\`, \`kotlin-*\`) | $VENDORED |"
  echo "| Coding standards & rules | $RULES |"
  echo
  echo "Rules by domain:"
  echo
  echo "| Domain | Files |"
  echo "|---|---|"
  printf '%s' "$domains"
  echo "$END"
} > "$block"

if ! grep -qF "$BEGIN" README.md; then
  echo -e "${RED}Marker not found in README.md — add the BEGIN/END inventory block first.${NC}" >&2
  rm -f "$block"; exit 1
fi

# awk -v cannot carry a multi-line value; splice from a file instead.
tmp=$(mktemp)
awk -v bf="$block" -v b="$BEGIN" -v e="$END" '
  index($0, b) { while ((getline line < bf) > 0) print line; close(bf); skip = 1; next }
  index($0, e) { skip = 0; next }
  !skip        { print }
' README.md > "$tmp"
rm -f "$block"

if [ "${1:-}" = "--check" ]; then
  if diff -q "$tmp" README.md >/dev/null; then
    echo -e "${GREEN}Inventory current${NC} — ${AGENTS} agents, ${OWN}+${VENDORED} skills, ${RULES} rules"
    rm -f "$tmp"
  else
    echo -e "${RED}README inventory is stale:${NC}"
    diff README.md "$tmp" | head -30
    echo -e "${RED}Run: ./scripts/generate-inventory.sh${NC}" >&2
    rm -f "$tmp"; exit 1
  fi
else
  mv "$tmp" README.md
  echo -e "${GREEN}Inventory written${NC} — ${AGENTS} agents, ${OWN}+${VENDORED} skills, ${RULES} rules"
fi
